chains:
  - chain: ethereum
    iso: eth
    type: evm
    driver: rpc
    workers:
      txid_worker_count: 0
      block_worker_count: 1
      transaction_worker_count: 5
    scan:
      depth: 10
      interval: 10s
    persist:
      capacity: 10
      duration: 9000h
    topics:
      transactions: eth-transactions
      blocks: eth-blocks
    rpc:
      node_url: http://eth:8545

  - chain: bitcoin
    iso: btc
    type: utxo
    driver: rpc
    workers:
      txid_worker_count: 3
      block_worker_count: 1
      transaction_worker_count: 5
    scan:
      depth: 10
      interval: 1s
    persist:
      bocks: 10
      duration: 1h
    topics:
      transactions: btc-transactions
      blocks: btc-blocks
    rpc:
      node_url: http://btc:password@btc:8332