version: "3.8"

services:
  watcher:
    image: golang:alpine
    tty: true
    working_dir: /app
    command: go run cmd/watcher/main.go
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - kafka

  kafka:
    image: bitnami/kafka:latest
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"

  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: watcher
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres

volumes:
  postgres:
  kafka: