x-app-env: &app-env
  GOMAXPROCS: 1
  APP_POSTGRES_HOST: postgres
  APP_POSTGRES_PORT: 5432
  APP_POSTGRES_USER: watcher_db_user
  APP_POSTGRES_PASSWORD: watcher_db_secret
  APP_POSTGRES_DATABASE: watcher_db

services:
  watcher:
    build:
      dockerfile: Dockerfile.dev
      context: .
    working_dir: /app
    environment:
      <<: *app-env
    volumes:
      - .:/app
      - /app/tmp
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: watcher_db_user
      POSTGRES_PASSWORD: watcher_db_secret
      POSTGRES_DB: watcher_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  btc:
    user: 1000:1000
    image: lncm/bitcoind:v28.0
    command:
      - "-prune=550"
      - "-maxuploadtarget=1440M"
      - "-testnet4=1"
#      - "-mainnet=1"
#      - "-regtest=1"
      - "-rpcuser=btc"
      - "-rpcallowip=0.0.0.0"
      - "-rpcpassword=password"
#      - "-txindex=1"
      - "-wallet=default"
      - "-zmqpubrawtx=tcp://0.0.0.0:28332"
      - "-zmqpubrawblock=tcp://0.0.0.0:28333"
    volumes:
      - btc:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 15m30s

volumes:
  btc:
  postgres_data: