version: "3.8"

services:
  watcher:
    image: golang:alpine
    tty: true
    working_dir: /app
    command: go run cmd/watcher/main.go
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  kafka: