FROM golang:1.26.1-alpine

ENV CGO_ENABLED=1

WORKDIR /app

RUN apk add --no-cache build-base
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
COPY . .

RUN go mod download

CMD ["air", "-c", ".air.toml"]