// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: state.sql

package database

import (
	"context"
)

const createState = `-- name: CreateState :exec
INSERT INTO state (
    key, value
) VALUES (
    $1, $2
 )
`

type CreateStateParams struct {
	Key   string
	Value []byte
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) error {
	_, err := q.db.Exec(ctx, createState, arg.Key, arg.Value)
	return err
}

const getByKey = `-- name: GetByKey :one
select key, value, created_at, updated_at from state where key = $1
`

func (q *Queries) GetByKey(ctx context.Context, key string) (State, error) {
	row := q.db.QueryRow(ctx, getByKey, key)
	var i State
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateState = `-- name: UpdateState :exec
UPDATE state SET value = $2, updated_at = current_timestamp
WHERE key = $1
`

type UpdateStateParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) error {
	_, err := q.db.Exec(ctx, updateState, arg.Key, arg.Value)
	return err
}
