// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LiquidCats/watcher/v2/internal/app/utxo/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// BlockPublisher is an autogenerated mock type for the BlockPublisher type
type BlockPublisher struct {
	mock.Mock
}

// PublishBlock provides a mock function with given fields: ctx, block
func (_m *BlockPublisher) PublishBlock(ctx context.Context, block *entities.Block) error {
	ret := _m.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for PublishBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Block) error); ok {
		r0 = rf(ctx, block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlockPublisher creates a new instance of BlockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockPublisher {
	mock := &BlockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
