// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockPublisher creates a new instance of MockBlockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockPublisher {
	mock := &MockBlockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockPublisher is an autogenerated mock type for the BlockPublisher type
type MockBlockPublisher struct {
	mock.Mock
}

type MockBlockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockPublisher) EXPECT() *MockBlockPublisher_Expecter {
	return &MockBlockPublisher_Expecter{mock: &_m.Mock}
}

// PublishBlock provides a mock function for the type MockBlockPublisher
func (_mock *MockBlockPublisher) PublishBlock(ctx context.Context, block entities.Block) error {
	ret := _mock.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for PublishBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Block) error); ok {
		r0 = returnFunc(ctx, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockPublisher_PublishBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBlock'
type MockBlockPublisher_PublishBlock_Call struct {
	*mock.Call
}

// PublishBlock is a helper method to define mock.On call
//   - ctx
//   - block
func (_e *MockBlockPublisher_Expecter) PublishBlock(ctx interface{}, block interface{}) *MockBlockPublisher_PublishBlock_Call {
	return &MockBlockPublisher_PublishBlock_Call{Call: _e.mock.On("PublishBlock", ctx, block)}
}

func (_c *MockBlockPublisher_PublishBlock_Call) Run(run func(ctx context.Context, block entities.Block)) *MockBlockPublisher_PublishBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Block))
	})
	return _c
}

func (_c *MockBlockPublisher_PublishBlock_Call) Return(err error) *MockBlockPublisher_PublishBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockPublisher_PublishBlock_Call) RunAndReturn(run func(ctx context.Context, block entities.Block) error) *MockBlockPublisher_PublishBlock_Call {
	_c.Call.Return(run)
	return _c
}
