// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient[TxIn any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient[TxIn] {
	mock := &MockClient[TxIn]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient[TxIn any] struct {
	mock.Mock
}

type MockClient_Expecter[TxIn any] struct {
	mock *mock.Mock
}

func (_m *MockClient[TxIn]) EXPECT() *MockClient_Expecter[TxIn] {
	return &MockClient_Expecter[TxIn]{mock: &_m.Mock}
}

// GetBlockByHash provides a mock function for the type MockClient
func (_mock *MockClient[TxIn]) GetBlockByHash(ctx context.Context, hash entities.BlockHash) (*entities.Block, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByHash")
	}

	var r0 *entities.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash) (*entities.Block, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash) *entities.Block); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.BlockHash) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBlockByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByHash'
type MockClient_GetBlockByHash_Call[TxIn any] struct {
	*mock.Call
}

// GetBlockByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash entities.BlockHash
func (_e *MockClient_Expecter[TxIn]) GetBlockByHash(ctx interface{}, hash interface{}) *MockClient_GetBlockByHash_Call[TxIn] {
	return &MockClient_GetBlockByHash_Call[TxIn]{Call: _e.mock.On("GetBlockByHash", ctx, hash)}
}

func (_c *MockClient_GetBlockByHash_Call[TxIn]) Run(run func(ctx context.Context, hash entities.BlockHash)) *MockClient_GetBlockByHash_Call[TxIn] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.BlockHash
		if args[1] != nil {
			arg1 = args[1].(entities.BlockHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetBlockByHash_Call[TxIn]) Return(block *entities.Block, err error) *MockClient_GetBlockByHash_Call[TxIn] {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockClient_GetBlockByHash_Call[TxIn]) RunAndReturn(run func(ctx context.Context, hash entities.BlockHash) (*entities.Block, error)) *MockClient_GetBlockByHash_Call[TxIn] {
	_c.Call.Return(run)
	return _c
}

// GetBlockByHashWithTransactions provides a mock function for the type MockClient
func (_mock *MockClient[TxIn]) GetBlockByHashWithTransactions(ctx context.Context, hash entities.BlockHash) (*entities.BlockWithTransactions[TxIn], error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByHashWithTransactions")
	}

	var r0 *entities.BlockWithTransactions[TxIn]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash) (*entities.BlockWithTransactions[TxIn], error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash) *entities.BlockWithTransactions[TxIn]); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.BlockWithTransactions[TxIn])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.BlockHash) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBlockByHashWithTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByHashWithTransactions'
type MockClient_GetBlockByHashWithTransactions_Call[TxIn any] struct {
	*mock.Call
}

// GetBlockByHashWithTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - hash entities.BlockHash
func (_e *MockClient_Expecter[TxIn]) GetBlockByHashWithTransactions(ctx interface{}, hash interface{}) *MockClient_GetBlockByHashWithTransactions_Call[TxIn] {
	return &MockClient_GetBlockByHashWithTransactions_Call[TxIn]{Call: _e.mock.On("GetBlockByHashWithTransactions", ctx, hash)}
}

func (_c *MockClient_GetBlockByHashWithTransactions_Call[TxIn]) Run(run func(ctx context.Context, hash entities.BlockHash)) *MockClient_GetBlockByHashWithTransactions_Call[TxIn] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.BlockHash
		if args[1] != nil {
			arg1 = args[1].(entities.BlockHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetBlockByHashWithTransactions_Call[TxIn]) Return(blockWithTransactions *entities.BlockWithTransactions[TxIn], err error) *MockClient_GetBlockByHashWithTransactions_Call[TxIn] {
	_c.Call.Return(blockWithTransactions, err)
	return _c
}

func (_c *MockClient_GetBlockByHashWithTransactions_Call[TxIn]) RunAndReturn(run func(ctx context.Context, hash entities.BlockHash) (*entities.BlockWithTransactions[TxIn], error)) *MockClient_GetBlockByHashWithTransactions_Call[TxIn] {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlock provides a mock function for the type MockClient
func (_mock *MockClient[TxIn]) GetLatestBlock(ctx context.Context) (*entities.Block, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlock")
	}

	var r0 *entities.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entities.Block, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entities.Block); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlock'
type MockClient_GetLatestBlock_Call[TxIn any] struct {
	*mock.Call
}

// GetLatestBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter[TxIn]) GetLatestBlock(ctx interface{}) *MockClient_GetLatestBlock_Call[TxIn] {
	return &MockClient_GetLatestBlock_Call[TxIn]{Call: _e.mock.On("GetLatestBlock", ctx)}
}

func (_c *MockClient_GetLatestBlock_Call[TxIn]) Run(run func(ctx context.Context)) *MockClient_GetLatestBlock_Call[TxIn] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetLatestBlock_Call[TxIn]) Return(block *entities.Block, err error) *MockClient_GetLatestBlock_Call[TxIn] {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockClient_GetLatestBlock_Call[TxIn]) RunAndReturn(run func(ctx context.Context) (*entities.Block, error)) *MockClient_GetLatestBlock_Call[TxIn] {
	_c.Call.Return(run)
	return _c
}

// GetMempool provides a mock function for the type MockClient
func (_mock *MockClient[TxIn]) GetMempool(ctx context.Context) ([]entities.TxID, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMempool")
	}

	var r0 []entities.TxID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.TxID, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.TxID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TxID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetMempool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMempool'
type MockClient_GetMempool_Call[TxIn any] struct {
	*mock.Call
}

// GetMempool is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter[TxIn]) GetMempool(ctx interface{}) *MockClient_GetMempool_Call[TxIn] {
	return &MockClient_GetMempool_Call[TxIn]{Call: _e.mock.On("GetMempool", ctx)}
}

func (_c *MockClient_GetMempool_Call[TxIn]) Run(run func(ctx context.Context)) *MockClient_GetMempool_Call[TxIn] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetMempool_Call[TxIn]) Return(txIDs []entities.TxID, err error) *MockClient_GetMempool_Call[TxIn] {
	_c.Call.Return(txIDs, err)
	return _c
}

func (_c *MockClient_GetMempool_Call[TxIn]) RunAndReturn(run func(ctx context.Context) ([]entities.TxID, error)) *MockClient_GetMempool_Call[TxIn] {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByTxID provides a mock function for the type MockClient
func (_mock *MockClient[TxIn]) GetTransactionByTxID(ctx context.Context, hash entities.TxID) (*entities.Transaction[TxIn], error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByTxID")
	}

	var r0 *entities.Transaction[TxIn]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TxID) (*entities.Transaction[TxIn], error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TxID) *entities.Transaction[TxIn]); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Transaction[TxIn])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.TxID) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetTransactionByTxID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByTxID'
type MockClient_GetTransactionByTxID_Call[TxIn any] struct {
	*mock.Call
}

// GetTransactionByTxID is a helper method to define mock.On call
//   - ctx context.Context
//   - hash entities.TxID
func (_e *MockClient_Expecter[TxIn]) GetTransactionByTxID(ctx interface{}, hash interface{}) *MockClient_GetTransactionByTxID_Call[TxIn] {
	return &MockClient_GetTransactionByTxID_Call[TxIn]{Call: _e.mock.On("GetTransactionByTxID", ctx, hash)}
}

func (_c *MockClient_GetTransactionByTxID_Call[TxIn]) Run(run func(ctx context.Context, hash entities.TxID)) *MockClient_GetTransactionByTxID_Call[TxIn] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.TxID
		if args[1] != nil {
			arg1 = args[1].(entities.TxID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetTransactionByTxID_Call[TxIn]) Return(transaction *entities.Transaction[TxIn], err error) *MockClient_GetTransactionByTxID_Call[TxIn] {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockClient_GetTransactionByTxID_Call[TxIn]) RunAndReturn(run func(ctx context.Context, hash entities.TxID) (*entities.Transaction[TxIn], error)) *MockClient_GetTransactionByTxID_Call[TxIn] {
	_c.Call.Return(run)
	return _c
}
