// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetBlockByHash provides a mock function for the type MockClient
func (_mock *MockClient) GetBlockByHash(ctx context.Context, hash entities.BlockHash, withTx bool) (entities.Block, error) {
	ret := _mock.Called(ctx, hash, withTx)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByHash")
	}

	var r0 entities.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash, bool) (entities.Block, error)); ok {
		return returnFunc(ctx, hash, withTx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.BlockHash, bool) entities.Block); ok {
		r0 = returnFunc(ctx, hash, withTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.BlockHash, bool) error); ok {
		r1 = returnFunc(ctx, hash, withTx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBlockByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByHash'
type MockClient_GetBlockByHash_Call struct {
	*mock.Call
}

// GetBlockByHash is a helper method to define mock.On call
//   - ctx
//   - hash
//   - withTx
func (_e *MockClient_Expecter) GetBlockByHash(ctx interface{}, hash interface{}, withTx interface{}) *MockClient_GetBlockByHash_Call {
	return &MockClient_GetBlockByHash_Call{Call: _e.mock.On("GetBlockByHash", ctx, hash, withTx)}
}

func (_c *MockClient_GetBlockByHash_Call) Run(run func(ctx context.Context, hash entities.BlockHash, withTx bool)) *MockClient_GetBlockByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.BlockHash), args[2].(bool))
	})
	return _c
}

func (_c *MockClient_GetBlockByHash_Call) Return(block entities.Block, err error) *MockClient_GetBlockByHash_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockClient_GetBlockByHash_Call) RunAndReturn(run func(ctx context.Context, hash entities.BlockHash, withTx bool) (entities.Block, error)) *MockClient_GetBlockByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockHash provides a mock function for the type MockClient
func (_mock *MockClient) GetLatestBlockHash(ctx context.Context) (entities.BlockHash, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockHash")
	}

	var r0 entities.BlockHash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (entities.BlockHash, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) entities.BlockHash); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(entities.BlockHash)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestBlockHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockHash'
type MockClient_GetLatestBlockHash_Call struct {
	*mock.Call
}

// GetLatestBlockHash is a helper method to define mock.On call
//   - ctx
func (_e *MockClient_Expecter) GetLatestBlockHash(ctx interface{}) *MockClient_GetLatestBlockHash_Call {
	return &MockClient_GetLatestBlockHash_Call{Call: _e.mock.On("GetLatestBlockHash", ctx)}
}

func (_c *MockClient_GetLatestBlockHash_Call) Run(run func(ctx context.Context)) *MockClient_GetLatestBlockHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetLatestBlockHash_Call) Return(blockHash entities.BlockHash, err error) *MockClient_GetLatestBlockHash_Call {
	_c.Call.Return(blockHash, err)
	return _c
}

func (_c *MockClient_GetLatestBlockHash_Call) RunAndReturn(run func(ctx context.Context) (entities.BlockHash, error)) *MockClient_GetLatestBlockHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetMempool provides a mock function for the type MockClient
func (_mock *MockClient) GetMempool(ctx context.Context) ([]entities.TxID, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMempool")
	}

	var r0 []entities.TxID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.TxID, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.TxID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TxID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetMempool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMempool'
type MockClient_GetMempool_Call struct {
	*mock.Call
}

// GetMempool is a helper method to define mock.On call
//   - ctx
func (_e *MockClient_Expecter) GetMempool(ctx interface{}) *MockClient_GetMempool_Call {
	return &MockClient_GetMempool_Call{Call: _e.mock.On("GetMempool", ctx)}
}

func (_c *MockClient_GetMempool_Call) Run(run func(ctx context.Context)) *MockClient_GetMempool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetMempool_Call) Return(txIDs []entities.TxID, err error) *MockClient_GetMempool_Call {
	_c.Call.Return(txIDs, err)
	return _c
}

func (_c *MockClient_GetMempool_Call) RunAndReturn(run func(ctx context.Context) ([]entities.TxID, error)) *MockClient_GetMempool_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByTxID provides a mock function for the type MockClient
func (_mock *MockClient) GetTransactionByTxID(ctx context.Context, hash entities.TxID) (entities.Transaction, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByTxID")
	}

	var r0 entities.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TxID) (entities.Transaction, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.TxID) entities.Transaction); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.TxID) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetTransactionByTxID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByTxID'
type MockClient_GetTransactionByTxID_Call struct {
	*mock.Call
}

// GetTransactionByTxID is a helper method to define mock.On call
//   - ctx
//   - hash
func (_e *MockClient_Expecter) GetTransactionByTxID(ctx interface{}, hash interface{}) *MockClient_GetTransactionByTxID_Call {
	return &MockClient_GetTransactionByTxID_Call{Call: _e.mock.On("GetTransactionByTxID", ctx, hash)}
}

func (_c *MockClient_GetTransactionByTxID_Call) Run(run func(ctx context.Context, hash entities.TxID)) *MockClient_GetTransactionByTxID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.TxID))
	})
	return _c
}

func (_c *MockClient_GetTransactionByTxID_Call) Return(transaction entities.Transaction, err error) *MockClient_GetTransactionByTxID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockClient_GetTransactionByTxID_Call) RunAndReturn(run func(ctx context.Context, hash entities.TxID) (entities.Transaction, error)) *MockClient_GetTransactionByTxID_Call {
	_c.Call.Return(run)
	return _c
}
