// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	data "github.com/LiquidCats/watcher/v2/internal/adapter/repository/rpc/utxo/data"
	entities "github.com/LiquidCats/watcher/v2/internal/app/kernel/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetBlockByHash provides a mock function with given fields: ctx, hash
func (_m *Client) GetBlockByHash(ctx context.Context, hash entities.BlockHash) (*data.Block, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByHash")
	}

	var r0 *data.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.BlockHash) (*data.Block, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.BlockHash) *data.Block); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.BlockHash) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBlockHash provides a mock function with given fields: ctx
func (_m *Client) GetLatestBlockHash(ctx context.Context) (entities.BlockHash, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockHash")
	}

	var r0 entities.BlockHash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entities.BlockHash, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entities.BlockHash); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entities.BlockHash)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMempool provides a mock function with given fields: ctx
func (_m *Client) GetMempool(ctx context.Context) ([]entities.TxID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMempool")
	}

	var r0 []entities.TxID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.TxID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.TxID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TxID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByTxId provides a mock function with given fields: ctx, hash
func (_m *Client) GetTransactionByTxId(ctx context.Context, hash entities.TxID) (*data.Transaction, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByTxId")
	}

	var r0 *data.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TxID) (*data.Transaction, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.TxID) *data.Transaction); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.TxID) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
