// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// EvmClient is an autogenerated mock type for the EvmClient type
type EvmClient struct {
	mock.Mock
}

// GetBlockByHash provides a mock function with given fields: ctx, hash
func (_m *EvmClient) GetBlockByHash(ctx context.Context, hash entities.BlockHash) (*interface{}, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByHash")
	}

	var r0 *interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.BlockHash) (*interface{}, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.BlockHash) *interface{}); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.BlockHash) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBlockHash provides a mock function with given fields: ctx
func (_m *EvmClient) GetLatestBlockHash(ctx context.Context) (entities.BlockHash, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockHash")
	}

	var r0 entities.BlockHash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entities.BlockHash, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entities.BlockHash); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entities.BlockHash)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByTxId provides a mock function with given fields: ctx, hash
func (_m *EvmClient) GetTransactionByTxId(ctx context.Context, hash entities.TxID) (*interface{}, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByTxId")
	}

	var r0 *interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TxID) (*interface{}, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.TxID) *interface{}); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.TxID) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEvmClient creates a new instance of EvmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EvmClient {
	mock := &EvmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
