// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// GetContractInfoByAddress provides a mock function for the type MockGetter
func (_mock *MockGetter) GetContractInfoByAddress(ctx context.Context, contract entities.Address) (*entities.Contract, error) {
	ret := _mock.Called(ctx, contract)

	if len(ret) == 0 {
		panic("no return value specified for GetContractInfoByAddress")
	}

	var r0 *entities.Contract
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Address) (*entities.Contract, error)); ok {
		return returnFunc(ctx, contract)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Address) *entities.Contract); ok {
		r0 = returnFunc(ctx, contract)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Contract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Address) error); ok {
		r1 = returnFunc(ctx, contract)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetter_GetContractInfoByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContractInfoByAddress'
type MockGetter_GetContractInfoByAddress_Call struct {
	*mock.Call
}

// GetContractInfoByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - contract entities.Address
func (_e *MockGetter_Expecter) GetContractInfoByAddress(ctx interface{}, contract interface{}) *MockGetter_GetContractInfoByAddress_Call {
	return &MockGetter_GetContractInfoByAddress_Call{Call: _e.mock.On("GetContractInfoByAddress", ctx, contract)}
}

func (_c *MockGetter_GetContractInfoByAddress_Call) Run(run func(ctx context.Context, contract entities.Address)) *MockGetter_GetContractInfoByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Address
		if args[1] != nil {
			arg1 = args[1].(entities.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetter_GetContractInfoByAddress_Call) Return(contract1 *entities.Contract, err error) *MockGetter_GetContractInfoByAddress_Call {
	_c.Call.Return(contract1, err)
	return _c
}

func (_c *MockGetter_GetContractInfoByAddress_Call) RunAndReturn(run func(ctx context.Context, contract entities.Address) (*entities.Contract, error)) *MockGetter_GetContractInfoByAddress_Call {
	_c.Call.Return(run)
	return _c
}
