// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler[T] {
	mock := &MockHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler[T any] struct {
	mock.Mock
}

type MockHandler_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockHandler[T]) EXPECT() *MockHandler_Expecter[T] {
	return &MockHandler_Expecter[T]{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockHandler
func (_mock *MockHandler[T]) Handle(ctx context.Context, value T) error {
	ret := _mock.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandler_Handle_Call[T any] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - value T
func (_e *MockHandler_Expecter[T]) Handle(ctx interface{}, value interface{}) *MockHandler_Handle_Call[T] {
	return &MockHandler_Handle_Call[T]{Call: _e.mock.On("Handle", ctx, value)}
}

func (_c *MockHandler_Handle_Call[T]) Run(run func(ctx context.Context, value T)) *MockHandler_Handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Handle_Call[T]) Return(err error) *MockHandler_Handle_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Handle_Call[T]) RunAndReturn(run func(ctx context.Context, value T) error) *MockHandler_Handle_Call[T] {
	_c.Call.Return(run)
	return _c
}
