// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockJob
func (_mock *MockJob) Handle(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJob_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockJob_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJob_Expecter) Handle(ctx interface{}) *MockJob_Handle_Call {
	return &MockJob_Handle_Call{Call: _e.mock.On("Handle", ctx)}
}

func (_c *MockJob_Handle_Call) Run(run func(ctx context.Context)) *MockJob_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJob_Handle_Call) Return(err error) *MockJob_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJob_Handle_Call) RunAndReturn(run func(ctx context.Context) error) *MockJob_Handle_Call {
	_c.Call.Return(run)
	return _c
}
