// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMapState creates a new instance of MockMapState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapState[K comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapState[K, V] {
	mock := &MockMapState[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMapState is an autogenerated mock type for the MapState type
type MockMapState[K comparable, V any] struct {
	mock.Mock
}

type MockMapState_Expecter[K comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockMapState[K, V]) EXPECT() *MockMapState_Expecter[K, V] {
	return &MockMapState_Expecter[K, V]{mock: &_m.Mock}
}

// Del provides a mock function for the type MockMapState
func (_mock *MockMapState[K, V]) Del(key K) {
	_mock.Called(key)
	return
}

// MockMapState_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockMapState_Del_Call[K comparable, V any] struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key K
func (_e *MockMapState_Expecter[K, V]) Del(key interface{}) *MockMapState_Del_Call[K, V] {
	return &MockMapState_Del_Call[K, V]{Call: _e.mock.On("Del", key)}
}

func (_c *MockMapState_Del_Call[K, V]) Run(run func(key K)) *MockMapState_Del_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapState_Del_Call[K, V]) Return() *MockMapState_Del_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockMapState_Del_Call[K, V]) RunAndReturn(run func(key K)) *MockMapState_Del_Call[K, V] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockMapState
func (_mock *MockMapState[K, V]) Get(key K) (V, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(K) (V, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(K) V); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(K) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockMapState_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMapState_Get_Call[K comparable, V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockMapState_Expecter[K, V]) Get(key interface{}) *MockMapState_Get_Call[K, V] {
	return &MockMapState_Get_Call[K, V]{Call: _e.mock.On("Get", key)}
}

func (_c *MockMapState_Get_Call[K, V]) Run(run func(key K)) *MockMapState_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapState_Get_Call[K, V]) Return(v V, b bool) *MockMapState_Get_Call[K, V] {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockMapState_Get_Call[K, V]) RunAndReturn(run func(key K) (V, bool)) *MockMapState_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockMapState
func (_mock *MockMapState[K, V]) Has(key K) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(K) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMapState_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockMapState_Has_Call[K comparable, V any] struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key K
func (_e *MockMapState_Expecter[K, V]) Has(key interface{}) *MockMapState_Has_Call[K, V] {
	return &MockMapState_Has_Call[K, V]{Call: _e.mock.On("Has", key)}
}

func (_c *MockMapState_Has_Call[K, V]) Run(run func(key K)) *MockMapState_Has_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapState_Has_Call[K, V]) Return(b bool) *MockMapState_Has_Call[K, V] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMapState_Has_Call[K, V]) RunAndReturn(run func(key K) bool) *MockMapState_Has_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockMapState
func (_mock *MockMapState[K, V]) Set(key K, value V) {
	_mock.Called(key, value)
	return
}

// MockMapState_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockMapState_Set_Call[K comparable, V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key K
//   - value V
func (_e *MockMapState_Expecter[K, V]) Set(key interface{}, value interface{}) *MockMapState_Set_Call[K, V] {
	return &MockMapState_Set_Call[K, V]{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockMapState_Set_Call[K, V]) Run(run func(key K, value V)) *MockMapState_Set_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapState_Set_Call[K, V]) Return() *MockMapState_Set_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockMapState_Set_Call[K, V]) RunAndReturn(run func(key K, value V)) *MockMapState_Set_Call[K, V] {
	_c.Run(run)
	return _c
}
