// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher[T] {
	mock := &MockPublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher[T any] struct {
	mock.Mock
}

type MockPublisher_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockPublisher[T]) EXPECT() *MockPublisher_Expecter[T] {
	return &MockPublisher_Expecter[T]{mock: &_m.Mock}
}

// PublishTo provides a mock function for the type MockPublisher
func (_mock *MockPublisher[T]) PublishTo(ctx context.Context, topic string, data T) error {
	ret := _mock.Called(ctx, topic, data)

	if len(ret) == 0 {
		panic("no return value specified for PublishTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, T) error); ok {
		r0 = returnFunc(ctx, topic, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_PublishTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTo'
type MockPublisher_PublishTo_Call[T any] struct {
	*mock.Call
}

// PublishTo is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - data T
func (_e *MockPublisher_Expecter[T]) PublishTo(ctx interface{}, topic interface{}, data interface{}) *MockPublisher_PublishTo_Call[T] {
	return &MockPublisher_PublishTo_Call[T]{Call: _e.mock.On("PublishTo", ctx, topic, data)}
}

func (_c *MockPublisher_PublishTo_Call[T]) Run(run func(ctx context.Context, topic string, data T)) *MockPublisher_PublishTo_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishTo_Call[T]) Return(err error) *MockPublisher_PublishTo_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_PublishTo_Call[T]) RunAndReturn(run func(ctx context.Context, topic string, data T) error) *MockPublisher_PublishTo_Call[T] {
	_c.Call.Return(run)
	return _c
}
