// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RpcCaller is an autogenerated mock type for the RpcCaller type
type RpcCaller struct {
	mock.Mock
}

// CallFor provides a mock function with given fields: ctx, dest, method, params
func (_m *RpcCaller) CallFor(ctx context.Context, dest interface{}, method string, params ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, method)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CallFor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, method, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRpcCaller creates a new instance of RpcCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRpcCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *RpcCaller {
	mock := &RpcCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
