// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockState creates a new instance of MockState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockState[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockState[T] {
	mock := &MockState[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockState is an autogenerated mock type for the State type
type MockState[T any] struct {
	mock.Mock
}

type MockState_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockState[T]) EXPECT() *MockState_Expecter[T] {
	return &MockState_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockState
func (_mock *MockState[T]) Get(ctx context.Context, key string) ([]T, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]T, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []T); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockState_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockState_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockState_Expecter[T]) Get(ctx interface{}, key interface{}) *MockState_Get_Call[T] {
	return &MockState_Get_Call[T]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockState_Get_Call[T]) Run(run func(ctx context.Context, key string)) *MockState_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockState_Get_Call[T]) Return(vs []T, err error) *MockState_Get_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockState_Get_Call[T]) RunAndReturn(run func(ctx context.Context, key string) ([]T, error)) *MockState_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockState
func (_mock *MockState[T]) Set(ctx context.Context, key string, value T) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, T) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockState_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockState_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *MockState_Expecter[T]) Set(ctx interface{}, key interface{}, value interface{}) *MockState_Set_Call[T] {
	return &MockState_Set_Call[T]{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockState_Set_Call[T]) Run(run func(ctx context.Context, key string, value T)) *MockState_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(T))
	})
	return _c
}

func (_c *MockState_Set_Call[T]) Return(err error) *MockState_Set_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockState_Set_Call[T]) RunAndReturn(run func(ctx context.Context, key string, value T) error) *MockState_Set_Call[T] {
	_c.Call.Return(run)
	return _c
}
