// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/adapter/repository/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateDB creates a new instance of MockStateDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateDB {
	mock := &MockStateDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateDB is an autogenerated mock type for the StateDB type
type MockStateDB struct {
	mock.Mock
}

type MockStateDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateDB) EXPECT() *MockStateDB_Expecter {
	return &MockStateDB_Expecter{mock: &_m.Mock}
}

// GetStateByKey provides a mock function for the type MockStateDB
func (_mock *MockStateDB) GetStateByKey(ctx context.Context, key string) (database.State, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetStateByKey")
	}

	var r0 database.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.State, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.State); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(database.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateDB_GetStateByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateByKey'
type MockStateDB_GetStateByKey_Call struct {
	*mock.Call
}

// GetStateByKey is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockStateDB_Expecter) GetStateByKey(ctx interface{}, key interface{}) *MockStateDB_GetStateByKey_Call {
	return &MockStateDB_GetStateByKey_Call{Call: _e.mock.On("GetStateByKey", ctx, key)}
}

func (_c *MockStateDB_GetStateByKey_Call) Run(run func(ctx context.Context, key string)) *MockStateDB_GetStateByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStateDB_GetStateByKey_Call) Return(state database.State, err error) *MockStateDB_GetStateByKey_Call {
	_c.Call.Return(state, err)
	return _c
}

func (_c *MockStateDB_GetStateByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (database.State, error)) *MockStateDB_GetStateByKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type MockStateDB
func (_mock *MockStateDB) SetState(ctx context.Context, arg database.SetStateParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.SetStateParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateDB_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockStateDB_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStateDB_Expecter) SetState(ctx interface{}, arg interface{}) *MockStateDB_SetState_Call {
	return &MockStateDB_SetState_Call{Call: _e.mock.On("SetState", ctx, arg)}
}

func (_c *MockStateDB_SetState_Call) Run(run func(ctx context.Context, arg database.SetStateParams)) *MockStateDB_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.SetStateParams))
	})
	return _c
}

func (_c *MockStateDB_SetState_Call) Return(err error) *MockStateDB_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateDB_SetState_Call) RunAndReturn(run func(ctx context.Context, arg database.SetStateParams) error) *MockStateDB_SetState_Call {
	_c.Call.Return(run)
	return _c
}
