// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// State is an autogenerated mock type for the State type
type State[T interface{}] struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, key
func (_m *State[T]) Get(ctx context.Context, key string) (T, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (T, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) T); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, key, value, period
func (_m *State[T]) Set(ctx context.Context, key string, value T, period time.Duration) error {
	ret := _m.Called(ctx, key, value, period)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, T, time.Duration) error); ok {
		r0 = rf(ctx, key, value, period)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewState creates a new instance of State. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewState[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *State[T] {
	mock := &State[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
