// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateDB creates a new instance of MockStateDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateDB {
	mock := &MockStateDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateDB is an autogenerated mock type for the StateDB type
type MockStateDB struct {
	mock.Mock
}

type MockStateDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateDB) EXPECT() *MockStateDB_Expecter {
	return &MockStateDB_Expecter{mock: &_m.Mock}
}

// SetBlockState provides a mock function for the type MockStateDB
func (_mock *MockStateDB) SetBlockState(ctx context.Context, chain entities.Chain, blocks []entities.BlockHash) error {
	ret := _mock.Called(ctx, chain, blocks)

	if len(ret) == 0 {
		panic("no return value specified for SetBlockState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Chain, []entities.BlockHash) error); ok {
		r0 = returnFunc(ctx, chain, blocks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateDB_SetBlockState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBlockState'
type MockStateDB_SetBlockState_Call struct {
	*mock.Call
}

// SetBlockState is a helper method to define mock.On call
//   - ctx context.Context
//   - chain entities.Chain
//   - blocks []entities.BlockHash
func (_e *MockStateDB_Expecter) SetBlockState(ctx interface{}, chain interface{}, blocks interface{}) *MockStateDB_SetBlockState_Call {
	return &MockStateDB_SetBlockState_Call{Call: _e.mock.On("SetBlockState", ctx, chain, blocks)}
}

func (_c *MockStateDB_SetBlockState_Call) Run(run func(ctx context.Context, chain entities.Chain, blocks []entities.BlockHash)) *MockStateDB_SetBlockState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Chain
		if args[1] != nil {
			arg1 = args[1].(entities.Chain)
		}
		var arg2 []entities.BlockHash
		if args[2] != nil {
			arg2 = args[2].([]entities.BlockHash)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStateDB_SetBlockState_Call) Return(err error) *MockStateDB_SetBlockState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateDB_SetBlockState_Call) RunAndReturn(run func(ctx context.Context, chain entities.Chain, blocks []entities.BlockHash) error) *MockStateDB_SetBlockState_Call {
	_c.Call.Return(run)
	return _c
}
