// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockState creates a new instance of MockState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockState[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockState[T] {
	mock := &MockState[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockState is an autogenerated mock type for the State type
type MockState[T any] struct {
	mock.Mock
}

type MockState_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockState[T]) EXPECT() *MockState_Expecter[T] {
	return &MockState_Expecter[T]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockState
func (_mock *MockState[T]) Get() []T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []T
	if returnFunc, ok := ret.Get(0).(func() []T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	return r0
}

// MockState_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockState_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockState_Expecter[T]) Get() *MockState_Get_Call[T] {
	return &MockState_Get_Call[T]{Call: _e.mock.On("Get")}
}

func (_c *MockState_Get_Call[T]) Run(run func()) *MockState_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockState_Get_Call[T]) Return(vs []T) *MockState_Get_Call[T] {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockState_Get_Call[T]) RunAndReturn(run func() []T) *MockState_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockState
func (_mock *MockState[T]) Set(value T) {
	_mock.Called(value)
	return
}

// MockState_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockState_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - value T
func (_e *MockState_Expecter[T]) Set(value interface{}) *MockState_Set_Call[T] {
	return &MockState_Set_Call[T]{Call: _e.mock.On("Set", value)}
}

func (_c *MockState_Set_Call[T]) Run(run func(value T)) *MockState_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockState_Set_Call[T]) Return() *MockState_Set_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockState_Set_Call[T]) RunAndReturn(run func(value T)) *MockState_Set_Call[T] {
	_c.Run(run)
	return _c
}
