// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LiquidCats/watcher/v2/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionPublisher creates a new instance of MockTransactionPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionPublisher {
	mock := &MockTransactionPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionPublisher is an autogenerated mock type for the TransactionPublisher type
type MockTransactionPublisher struct {
	mock.Mock
}

type MockTransactionPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionPublisher) EXPECT() *MockTransactionPublisher_Expecter {
	return &MockTransactionPublisher_Expecter{mock: &_m.Mock}
}

// PublishTransaction provides a mock function for the type MockTransactionPublisher
func (_mock *MockTransactionPublisher) PublishTransaction(ctx context.Context, transaction entities.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for PublishTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionPublisher_PublishTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTransaction'
type MockTransactionPublisher_PublishTransaction_Call struct {
	*mock.Call
}

// PublishTransaction is a helper method to define mock.On call
//   - ctx
//   - transaction
func (_e *MockTransactionPublisher_Expecter) PublishTransaction(ctx interface{}, transaction interface{}) *MockTransactionPublisher_PublishTransaction_Call {
	return &MockTransactionPublisher_PublishTransaction_Call{Call: _e.mock.On("PublishTransaction", ctx, transaction)}
}

func (_c *MockTransactionPublisher_PublishTransaction_Call) Run(run func(ctx context.Context, transaction entities.Transaction)) *MockTransactionPublisher_PublishTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Transaction))
	})
	return _c
}

func (_c *MockTransactionPublisher_PublishTransaction_Call) Return(err error) *MockTransactionPublisher_PublishTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionPublisher_PublishTransaction_Call) RunAndReturn(run func(ctx context.Context, transaction entities.Transaction) error) *MockTransactionPublisher_PublishTransaction_Call {
	_c.Call.Return(run)
	return _c
}
