name: Go Build and Deploy

on:
  release:
    types:
      - created

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    runs-on: ubuntu-latest

    needs:
      - tests

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Lowercase Repository Name
      id: repository
      uses: Entepotenz/change-string-case-action-min-dependencies@v1
      with:
        string: ${{ github.repository }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ github.event.release.tag_name }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ steps.repository.outputs.lowercase }}:latest

